CORE-516 Use botan submodule

diff --git a/android/external/downloads/Makefile b/android/external/downloads/Makefile
--- a/android/external/downloads/Makefile
+++ b/android/external/downloads/Makefile
@@ -13,8 +13,6 @@ include ../Makefile.conf
 #------------------------------------------------------------------------------#
 # Build parameters
 
-BOTAN_VERSION = 2.19.4_planck # default botan version if not provided
-
 ## Download all dependencies
 all: downloads.stamp
 
@@ -66,8 +64,13 @@ nettle-$(NETTLE_VERSION)-patched.tar.gz: nettle-$(NETTLE_VERSION).tar.gz
 	rm -rf nettle-$(NETTLE_VERSION)
 
 botan.src.stamp:
-	git clone git@github.com:plancksecurity/botan.git -b $(BOTAN_VERSION)
-	touch $@
+# just check the folder exist for the moment, so we use a submodule.
+	@if [ -d $(BOTAN_SRC) ]; then \
+		touch $@; \
+	else \
+		echo "Error: botan folder does not exist."; \
+		exit 1; \
+	fi
 
 nettle-$(NETTLE_VERSION).tar.gz:
 	wget -nc https://ftp.gnu.org/gnu/nettle/nettle-$(NETTLE_VERSION).tar.gz
